version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "eslint-plugin-n"
        versions: ["*"]