/**
 * {@link ActivityType} is the AniList ActivityType enum: the kind of an activity feed item.
 * Text and message entries are user-written; the list variants are generated by list updates.
 * @see https://docs.anilist.co/reference/enum/activitytype
 */
export type ActivityType = "TEXT" | "ANIME_LIST" | "MANGA_LIST" | "MESSAGE" | "MEDIA_LIST";

/**
 * {@link ActivityTypeMappings} is the allowlist of {@link ActivityType} values accepted by
 * the `type`/`type_not` filters of the activity queries; values outside it are rejected
 * before dispatch.
 * @see https://docs.anilist.co/reference/enum/activitytype
 */
export const ActivityTypeMappings: readonly ActivityType[] = [
    "TEXT",
    "ANIME_LIST",
    "MANGA_LIST",
    "MESSAGE",
    "MEDIA_LIST",
];
